/******************************************************************************/
/* editor_theme.go                                                            */
/******************************************************************************/
/* MIT License, Copyright (c) 2015-present Brent Farris, (John 4:13-14)       */
/******************************************************************************/

package editor_settings

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"unicode"

	"kaijuengine.com/matrix"
	"kaijuengine.com/platform/filesystem"
	"kaijuengine.com/platform/profiler/tracing"
)

const (
	themeFileName = "theme.json"
)

type workspaceGlobalCSS struct {
	contents string
	dirty    bool
}

// This is lazily populated from the workspace theme struct below as requested.
// Reloading the workspace sets this to an empty string
var globalCSS workspaceGlobalCSS

// WorkspaceTheme stores exposed theme values and serializes them to json.
// This makes working with themes slightly easier than altering CSS directly,
// and enforces the convention that all globally available theme values are
// always surfaced to stylesheets *and* Go code.
type WorkspaceTheme struct {
	ColorBackground  matrix.Color
	ColorContextBar  matrix.Color
	ColorPanel       matrix.Color
	ColorTextPassive matrix.Color
	ColorTextActive  matrix.Color
	SizeAreaMinimum  float32 `default:"0.1" visible:"false"`
	SizeContextBar   float32
	SizeTextGlobal   float32
	SizeRadiusGlobal float32
}

func (wt *WorkspaceTheme) setDefaults() {
	wt.ColorBackground = matrix.NewColor8(5, 6, 7, 255).AsColor()
	wt.ColorContextBar = matrix.NewColor8(9, 12, 15, 255).AsColor()
	wt.ColorPanel = matrix.NewColor8(14, 16, 18, 255).AsColor()
	wt.ColorTextPassive = matrix.NewColor8(154, 168, 159, 255).AsColor()
	wt.ColorTextActive = matrix.NewColor8(224, 226, 226, 255).AsColor()
	wt.SizeAreaMinimum = 0.1
	wt.SizeContextBar = 24
	wt.SizeTextGlobal = 12
	wt.SizeRadiusGlobal = 8
}

// MarkThemeCSSDirty discards the current theme CSS content
// so that it can be regenerated by a subsequent call to GetThemeCSS
func (wt *WorkspaceTheme) MarkGlobalCSSDirty() {
	globalCSS.dirty = true
}

// GetThemeCSS builds a CSS ":root" style block with values
// derived from the contents of the WorkspaceTheme struct.
// This Theme CSS is designed only to persist at runtime.
func (wt *WorkspaceTheme) GetGlobalCSS() string {
	if globalCSS.contents != "" && !globalCSS.dirty {
		return globalCSS.contents
	}
	themeValue := reflect.ValueOf(wt).Elem()
	themeType := themeValue.Type()
	if themeType.NumField() <= 0 {
		return ":root {}"
	}
	var output strings.Builder
	output.WriteString(":root {")
	for x := 0; x < themeType.NumField(); x++ {
		fieldInfo := themeType.Field(x)
		fieldValue := themeValue.Field(x)
		if fieldInfo.PkgPath != "" || !fieldValue.CanInterface() {
			continue
		}
		token, ter := toKebabCase(fieldInfo.Name)
		value, ver := universalValueAsString(&fieldInfo, &fieldValue)
		if ter == nil && ver == nil {
			fmt.Fprintf(&output, "\n\t--ed-%s: %s", token, value)
			continue
		}
		if ter != nil {
			slog.Error(fmt.Sprintf("Failed to tokenize field '%s'", fieldInfo.Name), "error", ter)
		}
		if ver != nil {
			slog.Error(fmt.Sprintf("Failed to write field value for '%s'", fieldInfo.Name), "error", ver)
		}
	}
	output.WriteString("\n}\n")
	globalCSS.contents = output.String()
	globalCSS.dirty = false
	return globalCSS.contents
}

func universalValueAsString(fieldInfo *reflect.StructField, fieldValue *reflect.Value) (string, error) {
	if fieldInfo == nil || fieldValue == nil || !fieldValue.IsValid() {
		return "", fmt.Errorf("provided type is nil or invalid")
	}
	if !fieldValue.CanInterface() {
		return "", fmt.Errorf("provided value is not accessible")
	}
	switch value := fieldValue.Interface().(type) {
	case matrix.Color:
		return value.Hex(), nil
	case float32:
		return strconv.FormatFloat(float64(value), 'g', -1, 32), nil
	case float64:
		return strconv.FormatFloat(value, 'g', -1, 64), nil
	case int:
		return strconv.Itoa(value), nil
	case int32:
		return strconv.FormatInt(int64(value), 10), nil
	case int64:
		return strconv.FormatInt(value, 10), nil
	default:
		return "", fmt.Errorf("type %s is not implemented for CSS conversion", value)
	}
}

func toKebabCase(input string) (string, error) {
	if input == "" {
		return "", fmt.Errorf("input string was empty")
	}
	var result strings.Builder
	for x, r := range input {
		if unicode.IsUpper(r) {
			if x > 0 {
				prev := rune(input[x-1])
				if unicode.IsLower(prev) || unicode.IsDigit(prev) {
					result.WriteByte('-')
				}
			}
			result.WriteRune(unicode.ToLower(r))
		} else {
			result.WriteRune(r)
		}
	}
	return result.String(), nil
}

// only one theme is supported for now

func (wt *WorkspaceTheme) Save() error {
	defer tracing.NewRegion("WorkspaceTheme.Save").End()
	appData, err := filesystem.GameDirectory()
	if err != nil {
		return AppDataMissingError{err}
	}
	f, err := os.Create(filepath.Join(appData, themeFileName))
	if err != nil {
		return WriteError{err, false}
	}
	if err := json.NewEncoder(f).Encode(*wt); err != nil {
		return WriteError{err, true}
	}
	return nil
}

func (wt *WorkspaceTheme) Load() error {
	defer tracing.NewRegion("Settings.Load").End()
	appData, err := filesystem.GameDirectory()
	if err != nil {
		return AppDataMissingError{err}
	}
	wt.setDefaults()
	path := filepath.Join(appData, themeFileName)
	if _, err := os.Stat(path); err != nil {
		return wt.Save()
	}
	f, err := os.Open(path)
	if err != nil {
		return ReadError{err, false}
	}
	if err := json.NewDecoder(f).Decode(wt); err != nil {
		return ReadError{err, true}
	}
	return nil
}
